---
# yaml-language-server: $schema=https://www.schemastore.org/dependabot-2.0.json
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'

  # Maintain dependencies for Python (poetry)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
