---
spring:
  main:
    web-application-type: none
bot:
  version: '@project.version@'
  token: ${BOT_TOKEN:}
  openai:
    org_id: ${OPENAI_ORG_ID:}
    api_key: ${OPENAI_API_KEY:}
    model: ${OPENAI_MODEL:}
